version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - MODEL_DIR=/app/models
      - DATA_DIR=/app/data
      - LOG_LEVEL=info
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

